### ISSUE TITLE
stacktrace in sync

### ISSUE THREAD

**Issue by dmscheidt** [clarete/s3sync#30]
Not sure if this is s3sync, or the aws-sdk:  

/var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/core/data.rb:117:in `method_missing': undefined method`has_key?' for #String:0x00000003ecc388 (NoMethodError)
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/core/response.rb:184:in `method_missing'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/s3/prefix_and_delimiter_collection.rb:31:in`each_member_in_page'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/s3/object_collection.rb:288:in `each_member_in_page'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/s3/paginated_collection.rb:31:in`_each_item'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/core/collection/with_limit_and_next_token.rb:54:in `_each_batch'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/core/collection.rb:80:in`each_batch'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/core/collection.rb:47:in `each'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/s3/object_collection.rb:282:in`each'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/lib/s3sync/sync.rb:305:in `to_a'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/lib/s3sync/sync.rb:305:in`read_tree_remote'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/lib/s3sync/sync.rb:317:in `read_trees'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/lib/s3sync/sync.rb:187:in`run'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/lib/s3sync/cli.rb:423:in `run'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/lib/s3sync/cli.rb:80:in`execute'
        from /var/lib/gems/1.9.1/gems/cmdparse-2.0.6/lib/cmdparse.rb:464:in `parse'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/lib/s3sync/cli.rb:462:in`run'
        from /var/lib/gems/1.9.1/gems/s3sync-2.0.2/bin/s3sync:66:in `<top (required)>'
        from /usr/local/bin/s3sync:23:in`load'
        from /usr/local/bin/s3sync:23:in `<main>'

This was done from a script that's attempting to sync a big chunk of stuff.  It made progress, and then crashed with this.  Restarting gave same trace immediately.

**Comment by QuAcK3RjAcK** [comment]
I had the same problem in the last days. It was a problem of special characters in the filename, in my case (i'm from germany) an "ü".

After fixing this, it works fine.
